### ISSUE TITLE
Dependency between `-T` and `--isolation`

### ISSUE THREAD

**Issue by pcotret** [QDucasse/gigue#5]
Starting from this loop: https://github.com/QDucasse/gigue/blob/main/gigue/cli.py#L186
```bash
python -m gigue  --isolation "fixer"
python -m gigue  --isolation "rimiss"
python -m gigue  --isolation "rimifull"
```
These commands won't work because they need the `-T` trampoline flag.
```bash
Traceback (most recent call last):
  File "/home/rocket/.pyenv/versions/3.9.16/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/rocket/.pyenv/versions/3.9.16/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/rocket/Documents/gigue/gigue/__main__.py", line 16, in <module>
    sys.exit(main())
  File "/home/rocket/Documents/gigue/gigue/cli.py", line 192, in main
    assert args.uses_trampolines
AssertionError
```
It may be useful to modify the assert message to get something more user-friendly:
```python
    elif args.isolation == "fixer":
        assert args.uses_trampolines,"Please enable the -T trampoline flag"
        gen_class = FIXERTrampolineGenerator
```

**Comment by QDucasse** [comment]
Fixed in [8ee2f9b](https://github.com/QDucasse/gigue/commit/8ee2f9b77fdf22525eac6ca958704a6dcb84125b).
